# Generated by Django 5.2.17 on 2026-09-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('titulo', models.CharField(max_length=150, verbose_name='titulo profissional')),
                ('subtitulo', models.CharField(blank=True, max_length=250, verbose_name='subtitulo profissional')),
                ('resumo', models.TextField(verbose_name='resumo profissional')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('linkedin', models.URLField(verbose_name='linkedin')),
            ],
            options={
                'verbose_name': 'perfil profissional',
                'verbose_name_plural': 'perfis profissionais',
            },
        ),
    ]
