# Generated by Django 5.2.17 on 2026-09-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.PositiveBigIntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='linkedin',
            field=models.URLField(max_length=300, verbose_name='linkedin'),
        ),
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='portfolio_perfil_id_igual_1'),
        ),
    ]
