# Generated by Django 5.2.17 on 2026-09-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_perfil_id_alter_perfil_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='titulo')),
                ('descricao', models.TextField(verbose_name='descricao')),
                ('categoria', models.CharField(choices=[('tubulacao_tig', 'Tubulação - TIG'), ('caldeiraria_fcaw', 'Caldeiraria - FCAW'), ('soldagem_mecanizada', 'Soldagem - FCAW')], max_length=50, verbose_name='categoria')),
                ('publicado', models.BooleanField(default=False, verbose_name='publicado')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'trabalho',
                'verbose_name_plural': 'trabalhos',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
