# Generated by Django 5.2.17 on 2026-09-05 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_trabalho'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(max_length=255, upload_to='trabalhos/%Y/%m/', verbose_name='imagem')),
                ('legenda', models.CharField(blank=True, max_length=250, verbose_name='legenda')),
                ('texto_alternativo', models.CharField(help_text='Descreva o que aparece na imagem para quem não pode ve-la.', max_length=250, verbose_name='texto alternativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='portfolio.trabalho', verbose_name='trabalho')),
            ],
            options={
                'verbose_name': 'imagem de trabalho',
                'verbose_name_plural': 'imagens de trabalhos',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
